import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from "@tanstack/react-query";
import { fetchProductsByCategory } from "@/lib/products-api";
import ProductsClient from "./Products";

type Props = {
  params: Promise<{ slug: string[] }>;
};

export async function generateMetadata({ params }: Props) {
  const { slug } = await params;
  const category = slug[0];

  return {
    title: `Products with ${category} category`,
    description: "Generated by create next app",
  };
}

// export const metadata: Metadata = {
//   title: "Products example title",
//   description: "Generated by create next app",
// };

export default async function Products({ params }: Props) {
  const { slug } = await params;
  const category = slug[0];

  const queryClient = new QueryClient();

  await queryClient.prefetchQuery({
    queryKey: ["products", { category }],
    queryFn: () => fetchProductsByCategory(category),
  });

  return (
    <div style={{ backgroundColor: "skyblue" }}>
      <HydrationBoundary state={dehydrate(queryClient)}>
        <ProductsClient />
      </HydrationBoundary>
    </div>
  );
}
