import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Products page title",
  description: "Generated by create next app",
};

export default function ProductsLayout({
  children,
  sidebar,
}: Readonly<{
  children: React.ReactNode;
  sidebar: React.ReactNode;
}>) {
  return (
    <div style={{ backgroundColor: "teal", display: "flex", gap: 12 }}>
      <Suspense fallback={<div>Loading categories...</div>}>{sidebar}</Suspense>
      {children}
    </div>
  );
}
